config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'page#index'
  get '/address', to: 'address#index'
  mount RailsAdmin::Engine => '/backstage', as: 'rails_admin'

  resources :stores, shallow: true, only: %i[index show] do
    # Frontend transaction pages
    resources :transactions, only: %i[new create] do
      member do
        patch :modify
        patch :save_draft
        patch :cancel
      end
    end
  end
  resources :transactions, only: %i[index show edit update]
  # Backend pages
  namespace :admin do
    resources :stores, shallow: true do
      resources :dishes do
        member do
          get :cancel
        end
      end
      resources :transactions, only: %i[index new create]
    end

    resources :transactions, only: %i[show edit update destroy] do
      member do
        # patch :act
        patch :accept
        patch :reject
        patch :pick
        patch :modify
        patch :save_draft
        patch :cancel
      end
    end
  end
end

app/models/store.rb
class Store < ApplicationRecord
  validates_presence_of :name, :tel, message: '*為必填欄位'
  validates_numericality_of :tel, in: 9..10, message: '請填寫正確的電話號碼（數字）'

  belongs_to :user
  has_many :transactions, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :dishes, -> { order(id: :asc) }, dependent: :destroy
  has_many :business_hours, dependent: :destroy
  has_and_belongs_to_many :store_tags, dependent: :destroy

  mount_uploader :main_img, MainImgUploader

  acts_as_paranoid

  # def self.get_all_store_latlng
  #   self.all.map do |store|
  #     store.to_json
  #   end
  # end
  

end

app/controllers/admin/stores_controller.rb
class Admin::StoresController < Admin::BaseController
  before_action :find_store, only: [:show, :edit, :update, :destroy]

  def index
    @stores = Store.all
  end

  def new
    @store = Store.new
  end

  def show
    # 後台只顯示自己的店面
    # @store = Store.find(current_user.id)
  end

  def create
    @store = Store.new(store_params)
    @store.user = current_user
    if @store.save
      redirect_to admin_store_path(@store), notice: '新增成功！'
    else
      render :new
    end
  end
  
  def edit
    # 驗證店主 或 管理員
    authorize @store
  end

  def update
    authorize @store
    if @store.update(store_params)
      redirect_to admin_store_path, notice: '更新成功！'
    else
      render :edit
    end
  end

  def destroy
    # 驗證店主 或 管理員
    authorize @store
    @store.destroy!
    redirect_to admin_stores_path, notice: '商店已刪除'
  end

  private

  def find_store
    @store = Store.includes(:dishes).find_by(id: params[:id])
  end

  def store_params
    params.require(:store).permit(:name, :description, :location, :latitude, :tel, :main_img)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :find_store, only: [:show]

  def index
    # Fuzzy search "ILIKE" is pg only
    # search: # => keyword argument
    @stores = list_stores(search: params[:search])
    render 'page/index'
  end

  def show
    @store = Store.find(params[:id])
    # @dishes = @store.dishes
  end

  private

  def list_stores(search: nil)
    return Store.all if search.nil?

    Store.where('name ILIKE ?', "%#{params[:search]}%")
  end

  def find_store
    @store = Store.find_by(id: params[:id])
  end

  def store_params
    params.require(:store).permit(:name, :description, :tel)
  end

end

app/helpers/admin/store_helper.rb
module Admin
  module StoreHelper
    def flash_message(msg_type)
      %Q(<p class="#{msg_type} error_messages">#{flash[msg_type]}</p>).html_safe
    end

    def error_block(store)
      msg = []
      if store.errors.any? 
        msg << '<ul class="error_messages">'
        store.errors.full_messages.each do |message|
          msg << "<li>#{message}</li>"
        end
        msg << "</ul>"
      end
      sanitize(msg.join(''))
    end
  end
end

app/helpers/store_helper.rb
module StoreHelper
  def stores
    @store = Store.all
  end
end

app/views/admin/stores/_dish_list_items.erb
<% @store.dishes.each do |dish| %>
  <div id="dish_id_<%= dish.id %>" class="dishes__card dish_state_<%= dish.state %>">
    <div class="dishes__card--desc">
      <p><%= dish.name %></p>
      <p><%= dish.price %></p>
    </div>
    <div class="dish__img">
      <%= image_tag dish.main_img_url if dish.main_img? %>
    </div>
    <%= link_to fa_icon('edit'), edit_admin_dish_path(dish), remote: true, class: 'btn btn-warning btn--function' if policy(@store).edit? %>
    <%= link_to fa_icon('trash'), admin_dish_path(dish), method: 'delete', remote: true, data: { confirm: '確認刪除商品？' }, class: 'btn btn-danger btn--function' if policy(@store).edit? %>
  </div>
<% end %>

app/views/admin/stores/_dish_list_items.html.erb
<% @store.dishes.each do |dish| %>
  <div id="dish_id_<%= dish.id %>" class="col-12 col-md-5 dishes__card dish_state_<%= dish.state %>">
    <div class="dishes__card--desc">
      <p><%= dish.name %></p>
      <p><%= dish.price %></p>
    </div>
    <div class="dish__img">
      <%= image_tag dish.main_img_url if dish.main_img? %>
    </div>
    <div class="dishes__card--btn" >
      <%= link_to fa_icon('edit'), edit_admin_dish_path(dish), remote: true, class: 'btn btn-sm btn-warning btn--function edit-btn' if policy(@store).edit? %>
      <%= link_to fa_icon('trash'), admin_dish_path(dish), method: 'delete', remote: true, data: { confirm: '確認刪除商品？' }, class: 'btn btn-sm btn-danger btn--function trash-btn' if policy(@store).edit? %>
  </div>
  </div>
<% end %>

app/views/admin/stores/_form.html.erb
<%= error_block(@store) %>
<%= form_for [:admin, store] , html: { id: 'store_form'} do |f| %>
  <div>
    <%= f.label :name, '店名' %>
    <%= f.text_field :name, id: 'name' %>
  </div>
  <div>
    <%= f.label :description, '描述' %>
    <%= f.text_area :description, id: 'description' %>
  </div>
  <div>
    <%= f.label :location, '地址' %>
    <%= f.text_field :location, id: 'location' %>
  </div>
  <div>
    <%= f.label :tel, '電話' %>
    <%= f.text_field :tel, id: 'tel' %>
  </div>
  <div>
    <%= f.label :main_img, '首頁圖' %>
    <%= f.file_field :main_img, id: 'main_img' %>
  </div>
    <%= f.submit class: 'btn btn-info' %>
<% end %>

app/views/admin/stores/edit.html.erb
<div class="edit_store_page">   
  <h1>編輯商店</h1>
  <div class="edit_st_list">
  <%#= link_to "建立商店", new_admin_store_path, class: 'btn btn-info' %>
    <%= render 'form', store: @store %>
    <%= link_to "返回", admin_store_path(@store), class: 'btn btn-info' %>
  </div>
</div>

app/views/admin/stores/index.html.erb
<div class="my_store">  
  <h1>我的商店</h1>
  <% if user_signed_in? %>
    <%#= link_to '我的商店', admin_store_path(), class: 'btn btn-info' %>
    <%= link_to '建立商店', new_admin_store_path, class: 'btn btn-info' %>
  <% end %>
</div> 
<div class='store__list container d-flex flex-wrap justify-content-center'>
  <div class="row justify-content-center">
  <% @stores.each do |store| %>
    <div class='store__list--item col-12 col-md-6 col-xl-4 mb-2'>
      <div class="card store__card">
        <div class='store__card--img'>
          <% if store.main_img? %>
          <%= link_to image_tag(store.main_img_url, class: 'card-img-top' ), admin_store_path(store) %>
          <% else %>
          <%= link_to image_tag('bg_default.jpg', class: 'card-img-top'), admin_store_path(store) %>
          <% end %>
        </div>
        <div class='store-detail card-body'>
          <h3 class='card-title'><%= store.name %></h3>
          <p class='card-desc'>描述：<%= store.description %></p>
          <p>地址：<%= store.location %></p>
          <p>電話：<%= store.tel %></p><br />
          <div class="admin_store_btn">
            <%= link_to '查看', admin_store_path(store), class: 'btn btn-info' %>
            <%= link_to '編輯商店', edit_admin_store_path(store), class: 'btn btn-warning' if policy(store).edit? %>
            <%= link_to '關店', admin_store_path(store), method: 'delete', class: 'btn btn-danger', data: { confirm: '確認關店？'} if policy(store).destroy? %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/admin/stores/new.html.erb
<div class="add_store_page">  
  <h1>建立商店</h1>
  <div class="add_st_list">
    <%#= link_to "建立商店", new_admin_store_path, class: 'btn btn-info' %>
    <%= render 'form', store: @store %>
  </div>
</div>

app/views/admin/stores/show.html.erb
<h1><%= @store.name %></h1>

<div class="container">
  <div class="show--store__header col-12">
    <p>店家資訊 ：<%= @store.description %></p>
    <p>店家地址 ：<%= @store.location %></p>
  </div>

  <div class="row">
    <div class="show--store__body col-12 col-md-8">
      <section class="dishes">
        <div class="dishes__list">
          <%= render 'dish_list_items' %>
          <%= render './admin/dishes/new_dish_card' if policy(@store).edit? %>
        </div>
      </section>
    </div>
    <div class="show--store__info col-12 col-md-4">
      <div class="show--store__main_img">
        <%= image_tag @store.main_img.thumb.url if @store.main_img? %>
      </div>
      <%= link_to fa_icon('eye', text: '查看訂單'), admin_store_transactions_path(@store), class: 'btn btn-info' if policy(@store).edit? %>
      <%= link_to fa_icon("edit", text: "編輯店面", right: true), edit_admin_store_path(@store), class: 'btn btn-warning' if policy(@store).edit? %>
    </div>
  </div>
</div>