config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'page#index'
  get '/address', to: 'address#index'
  mount RailsAdmin::Engine => '/backstage', as: 'rails_admin'

  resources :stores, shallow: true, only: %i[index show] do
    # Frontend transaction pages
    resources :transactions, only: %i[new create] do
      member do
        patch :modify
        patch :save_draft
        patch :cancel
      end
    end
  end
  resources :transactions, only: %i[index show edit update]
  # Backend pages
  namespace :admin do
    resources :stores, shallow: true do
      resources :dishes do
        member do
          get :cancel
        end
      end
      resources :transactions, only: %i[index new create]
    end

    resources :transactions, only: %i[show edit update destroy] do
      member do
        # patch :act
        patch :accept
        patch :reject
        patch :pick
        patch :modify
        patch :save_draft
        patch :cancel
      end
    end
  end
end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < Admin::BaseController
  before_action :find_store, only: %i[index show]
  before_action :find_transaction, only: %i[accept modify reject pick]
  before_action :authenticate_user!

  def index
    if (current_user.stores.ids.include? @store.id) || (current_user.role == 'admin')
      @transactions = @store.transactions.order(created_at: :desc)
    else
      redirect_to(request.referrer || root_path)
    end

    # options 2:
    # @transactions = policy_scope(Transaction)
  end

  # def show
  #   @transaction = Transaction.includes(:user, :dish).find(params[:id])
  # end

  def new
  end

  def edit
  end

  def update
    @transaction = Transaction.find(params[:id])
    if @transaction.update(transaction_params)
      render 'update'
    else
      render 'edit'
    end
  end

  def destroy
  end

  def accept
    @transaction.accept!
    render 'state_change'
  end

  def modify
    @transaction.modify!
    render 'edit'
  end

  def reject
    @transaction.reject!
    render 'state_change'
  end

  def pick
    @transaction.pick!
    render 'state_change'
  end

  # 舊版寫法參考用
  # def act
  #   @transaction = Transaction.find(params[:id])
  #   case params[:act]
  #   when 'accept'
  #     @transaction.accept!
  #     render 'act'
  #   when 'modify'
  #     @transaction.modify!
  #     render 'edit'
  #   when 'pick'
  #     @transaction.pick!
  #     render 'act'
  #   when 'reject'
  #     @transaction.reject!
  #     render 'act'
  #   end
  # end

  private

  def find_store
    @store = Store.includes(transactions: [:user, transaction_items: [:dish]]).find(params[:store_id])
  end

  def transaction_params
    params.require(:transaction).permit(:description, :pick_up_time)
  end

  def find_transaction
    @transaction = Transaction.includes(:users, :dishes).find(params[:id])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :find_transaction, only: %i[modify save_draft cancel]

  def index
    @transactions = current_user.transactions.order('created_at desc')
  end

  def create
    @store = Store.find(params[:store_id])
    @transaction = @store.transactions.create(user: current_user, total_price: 0)

    @transaction.pick_up_time = default_pick_up_time(params[:time])

    @transaction.description = (params[:description])
    @transaction.save

    build_dish_item.each do |_index, col|
      t = @transaction.transaction_items.new(col)
      t.save!
    end
  end

  def update
    @transaction = Transaction.find(params[:id])
    if @transaction.update(transaction_params)
      render 'update'
    else
      render 'edit'
    end
  end

  def modify
    @transaction.modify!
    render 'edit'
  end

  def save_draft
    @transaction.save_draft!
    render 'state_change'
  end

  def cancel
    @transaction.cancel!
    render 'state_change'
  end

  private

  def find_transaction
    @transaction = Transaction.find(params[:id])
  end

  def build_dish_item
    dishes = JSON.parse(params[:dishes]) rescue {}
    ids = dishes.map { |k, _| k.to_i }
    rs = {}
    Dish.where(id: ids).each do |dish|
      count = dishes[dish.id.to_s].to_i
      rs["item#{dish.id}"] = {
        'dish_id' => dish.id,
        'dish_count' => count,
        'item_price' => dish.price
      }
    end
    rs
  end

  def transaction_params
    params.require(:transaction).permit(:description, :pick_up_time)
  end
end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/views/transactions/_modify_orders__card--body.html.erb
<div class="orders__card--info">
  <h2 class="orsers_card--title">修改訂單</h2>
  <%= form_for transaction, html: { remote: true, class: 'modify_order_form', id: 'order_form'} do |f| %>
  <div class="form-group">
    <%= f.label :pick_up_time, "調整取餐時間" %>
    <%= f.datetime_field :pick_up_time, value: default_pick_up_time(transaction.pick_up_time) ,id: 'pick_up_time' %>
  </div>
  <div class="form-group">
    <%= f.label :description, "修改訂單備註" %>
    <%= f.text_area :description, id: 'description' %>
  </div>
  <%= f.submit class: 'btn btn-info' %>
  <% end %>
</div>

app/views/transactions/_orders__card--body.html.erb
<div class='orders__card--info'>
  <p>訂單編號：<%= t.serial_number %> ｜ 訂單狀態：<%= t.state %> ｜ 預計取餐時間：<%= t.pick_up_time %></p>
  <p>商店名稱：<%= t.store.name %> ｜ 聯絡電話：<%= t.store.tel %></p>
  <p>訂單備註：<%= t.description %></p>
</div>
<div class='orders__card--items__list row col-12'>
  <% t.transaction_items.each do |ti| %>
    <div class='transaction_items__detail'>
    <p>
      <span><%= ti.dish.name %>（<%= ti.item_price.round %>元）* <%= ti.dish_count %> 份</span>
    </p>
  </div>
  <% end %>
  <p class='row col-12'><strong>訂單總額：<%= t.total_price %></strong></p>
</div>
<div class='orders__card--function_buttons row col-12 mb-2'>
  <%= link_to '確認送出', save_draft_transaction_path(t), method: 'patch', remote: true, class: 'btn btn-success mr-2' if t.may_save_draft? %>
  <%= link_to '修改', modify_transaction_path(t), method: 'patch', remote: true, class: 'btn btn-warning mr-2' if t.may_modify? %>
  <%= link_to '取消', cancel_transaction_path(t), method: 'patch', remote: true, class: 'btn btn-danger mr-2' if t.may_cancel? %>
</div>

app/views/transactions/edit.js.erb
$('#order_<%= @transaction.id %>').html('<%= j render "modify_orders__card--body", transaction: @transaction %>')

<% @transaction.errors.full_messages.each do |message| %>
  $('#helpBlock').append('<p class="notice"><%= message %></p>')
<% end %> 

app/views/transactions/index.html.erb
<div class='orders__container container'>
  <div class='row'>
    <div class='orders__header col-12'>
      <h1>訂單列表</h1>
    </div>
  </div>
  <div class='row'>
    <main class='orders__list col-12'>
      <% @transactions.each do |t| %>
      <div id='order_<%= t.id %>' class='user-orders__card orders__card row col-12'>
        <%= render 'orders__card--body', t: t %>
      </div>
      <% end %>
    </main>
  </div>
</div>

app/views/transactions/state_change.js.erb
$('#order_<%= @transaction.id %>').html('<%= j render "orders__card--body", t: @transaction %>')

app/views/transactions/update.js.erb
$('#order_<%= @transaction.id %>').html('<%= j render "orders__card--body", t: @transaction %>')